services:
  bot:
    image: discord-music-bot
    depends_on:
      - lavalink
    deploy:
      &deploy_default
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 15s
    env_file:
      - .env

  lavalink:
    image: fredboat/lavalink:9abd5d0
    deploy:
      <<: *deploy_default
    volumes:
      - ./lavalink.yaml:/opt/Lavalink/application.yaml
