services:
  discord-music-bot-service:
    container_name: discord_music_bot
    image: discord_music_bot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 15s
    env_file:
      - .env
